### ISSUE TITLE
Conflict with Kerbal Construction Time

### ISSUE THREAD

**Issue by TheBeesElise** [linuxgurugamer/SettingsMaster#1]
When I have SettingsMaster 0.0.2.2 installed alongside Kerbal Construction Time 1.4.0.69 the prelaunch kerbal assignment menu does not appear when called. The primary window still launched as normal. The game doesn't crash so I can't get much more specific than that.

**Comment by linuxgurugamer** [comment]
Please remove SettingsMaster,  It doesn't work and breaks the game, as you just found out.
this was stated on the main thread on the forums
