### ISSUE TITLE
Unintentional behaviors at game start.

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/SettingsMaster#3]
SettingsMaster will disable the custom settings pages of mods (it's seems random) when the count exceeds 16; this is by design.  Unfortunately, this process also prevents those pages from generating custom settings to be stored in the savefile.sfs PARAMETERS{} section resulting in these:

181028T221347.867 [WARNING] [GameParameters.LoadCustomNode] [GameParameters]: Couldn't find type for custom parameter FMRS_Settings.
181028T221347.868 [WARNING] [GameParameters.LoadCustomNode] [GameParameters]: Couldn't find type for custom parameter KRASH_Settings.
181028T221347.868 [WARNING] [GameParameters.LoadCustomNode] [GameParameters]: Couldn't find type for custom parameter StateFundingSettings.
181028T221347.868 [WARNING] [GameParameters.LoadCustomNode] [GameParameters]: Couldn't find type for custom parameter ABCORSSettings.
181028T221347.869 [WARNING] [GameParameters.LoadCustomNode] [GameParameters]: Couldn't find type for custom parameter CrewRandRCustomParams.

Once the game is begun EXCEPTIONS can be thrown for any mod without custom parameters set.

181028T221349.488 [EXCEPTION] [GameParameters.CustomParams[StateFundingSettings]] ArgumentException: Couldn't find custom parameter StateFundingSettings!
   at GameParameters.CustomParams[StateFundingSettings] ()
   at StateFunding.ViewManager.OnGUI ()
181028T221925.106 [EXCEPTION] [GameParameters.CustomParams[FMRS_Settings]] ArgumentException: Couldn't find custom parameter FMRS_Settings!
   at GameParameters.CustomParams[FMRS_Settings] ()
   at FMRS.FMRS_Space_Center.ReloadSettings ()
   at EventVoid.Fire ()
   at UnityEngine.Debug:LogException(Exception)
   at EventVoid:Fire()
   at MiniSettings:ApplySettings()
   at MiniSettings:<drawWindow>m__3()
   at DialogGUIButton:OptionSelected()
   at DialogGUIButton:<Create>m__7()
   at UnityEngine.EventSystems.EventSystem:Update()

**Comment by linuxgurugamer** [comment]
Please don't use this, it doesn't do what it was supposed to because I can't use Reflection.

**Comment by 7ranceaddic7** [comment]
Noted.  Too bad, solid idea.

**Comment by linuxgurugamer** [comment]
Yes.  I have it working, but can't release it because it uses reflection to get internals of KSP, which is against the forum rules.  I even asked for permission.  But at least they got the bug fixed fairly quickly
I may revisit this, want to see if they opened up some more of the API, but for now, I'm removing it from CKAN

**Comment by 7ranceaddic7** [comment]
So, if I were to, oh, i dunno, say, compile this code myself, I'd have a working dll??

**Comment by linuxgurugamer** [comment]
No, because I didn't upload the code.
